### ISSUE TITLE
resolver: make it smarter

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-records-editor-js#9]
~~Remove router functionality~~

Router is used to parse `:type` and `:id` url params, so it can load the relevant config.

- [x] record: we provide record id and specific configuration for that record type from invenio
- [x] schema: this is resolved from the record itself or we can provided it additionally from invenio
- [x] config: comes from invenio and gets merged with the existing one of the editor
- [x] when there is a schema from invenio use that one instead of fetching sequentially.

**Comment by topless** [comment]
Note to self: apparently the components that boostrap the application cannot take input. I went for a work around on the work around in order to load a config in the editor from invenio. 

Also angular cannot access (obviously) elements outside of the application scope, ViewChild off the window. I went old school on this one, plain javascript inside an angular service.

@zzacharo in the same horrific fashion we can also pass the record, schema .. and so.
